# Optional files used to create an individual nights throughput_correction, flux_calibration and telluric_correction data.
# sky_flat and calib_star are required. absolute_flux_cal, telluric_correction, and response will be calculated if not given
files_for_generating_calibration_data:  # Links to the location of the .fits files containing calibration star images
  - calib_star:
      - src/koala/data/385R/CALIBRATION_STARS/10mar20082red.fits
      - src/koala/data/385R/CALIBRATION_STARS/10mar20083red.fits
      - src/koala/data/385R/CALIBRATION_STARS/10mar20084red.fits
    absolute_flux_cal: src\koala\data\385R\CALIBRATION_STARS\H600_385R_0p6_1k25_integrated_star_flux.dat
    telluric_correction: src\koala\data\385R\CALIBRATION_STARS\H600_385R_0p6_1k25_telluric_correction.dat
    response: src\koala\data\385R\CALIBRATION_STARS\H600_385R_0p6_1k25_response.dat
    name: H600
  - calib_star:
      - src/koala/data/385R/CALIBRATION_STARS/10mar20094red.fits
      - src/koala/data/385R/CALIBRATION_STARS/10mar20095red.fits
      - src/koala/data/385R/CALIBRATION_STARS/10mar20096red.fits
    absolute_flux_cal:
    telluric_correction:
    response:
    name: HR3454_A
